<?php
require_once __DIR__.'/survey_app.php';
require_once __DIR__.'/language.php';
$locale=currentLanguage()==='fr'?'fr':'en';$hub=static fn($en,$fr)=>$locale==='fr'?$fr:$en;
[$role,$staff]=sv_staff();
if($role!==$questionHubRole)sv_fail('Accès réservé à votre espace.',403);
$params=[];$scope='';
if($role==='professor'){$scope=' WHERE EXISTS (SELECT 1 FROM professor_content_assignments p WHERE p.theme_id=t.id AND p.professor_id=? AND p.chapter_id IS NULL)';$params=[$staff];}
$st=$pdo->prepare('SELECT t.id,t.name,d.id AS definition_id,d.status,d.survey_json FROM themes t LEFT JOIN survey_definitions d ON d.id=(SELECT MAX(v.id) FROM survey_definitions v WHERE v.theme_id=t.id)'.$scope.' ORDER BY t.name');$st->execute($params);$themes=$st->fetchAll(PDO::FETCH_ASSOC);
$theme=(int)($_GET['theme_id']??0);$selected=null;
foreach($themes as $row)if((int)$row['id']===$theme)$selected=$row;
if($theme&&!$selected)sv_theme_access($theme);
$schema=$selected&&$selected['survey_json']?json_decode($selected['survey_json'],true,64,JSON_THROW_ON_ERROR):null;
$questions=$schema?array_values(array_filter(sv_questions($schema),static fn($q)=>!($q['assessmentOnly']??false))):[];
$title=static function($value)use($locale):string{if(is_array($value))$value=$value[$locale]??$value['default']??$value['fr']??reset($value);return strip_tags((string)$value);};
$typesFr=['text'=>'Réponse courte','comment'=>'Réponse libre','multipletext'=>'Plusieurs réponses libres','radiogroup'=>'Choix unique','checkbox'=>'Choix multiples','dropdown'=>'Liste de choix','ranking'=>'Classement','matrix'=>'Tableau','matrixdropdown'=>'Tableau de choix','boolean'=>'Oui / Non','rating'=>'Échelle'];

$typesEn=['text'=>'Short answer','comment'=>'Open answer','multipletext'=>'Multiple open answers','radiogroup'=>'Single choice','checkbox'=>'Multiple choices','dropdown'=>'Dropdown','ranking'=>'Ranking','matrix'=>'Matrix','matrixdropdown'=>'Choice matrix','boolean'=>'Yes / No','rating'=>'Scale'];$types=$locale==='fr'?$typesFr:$typesEn;
$displayMarks=static function($q)use($hub){if(!($q['responseOnly']??false))return (string)($q['maxScore']??0);if(preg_match('/^(\d+(?:\.\d+)?)/',(string)($q['sourceRubric']??''),$match))return $match[1].' '.$hub('(shared)','(partagés)');return $hub('Shared criterion','Critère partagé');};
?><!doctype html><html lang="<?= qp_h($locale) ?>"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Questions</title><link rel="stylesheet" href="../assets/survey/staff.css"></head><body><?php $staffRoot='../';require __DIR__.'/survey_staff_header.php'; ?><main class="staff-shell">

<h1>Questions</h1><p><?= qp_h($hub('Choose a theme, then add or edit its questions. After publication, new attempts use your changes.','Choisissez un thème, puis ajoutez ou modifiez ses questions. Après publication, les nouvelles passations utilisent vos changements.')) ?></p>
<form method="get" class="staff-card staff-actions"><input type="hidden" name="lang" value="<?= qp_h($locale) ?>"><label for="theme"><?= qp_h($hub('Theme','Thème')) ?></label><select id="theme" name="theme_id" required><option value=""><?= qp_h($hub('Choose a theme','Choisir un thème')) ?></option><?php foreach($themes as $row):?><option value="<?= (int)$row['id'] ?>" <?= $theme===(int)$row['id']?'selected':'' ?>><?= qp_h($row['name']) ?><?= $row['definition_id']?'':qp_h($hub(' — to create',' — à créer')) ?></option><?php endforeach;?></select><button><?= qp_h($hub('Show questions','Afficher les questions')) ?></button></form>
<?php if(!$themes):?><p><?= qp_h($hub('No full theme is assigned to you. Your question bank by chapter remains available below.','Aucun thème complet ne vous est attribué. Votre banque de questions par chapitre reste accessible ci-dessous.')) ?></p><?php endif;?>
<?php if($selected):?><section class="staff-card"><h2><?= qp_h($selected['name']) ?></h2><p><?= count($questions) ?> questions · <?= !$schema?$hub('To create','À créer'):($selected['status']==='published'?$hub('Published','Publié'):($selected['status']==='draft'?$hub('Draft — changes to publish','Brouillon — modifications à publier'):$hub('Archived','Archivé'))) ?></p>
<div class="staff-actions"><a class="staff-button" href="../survey_creator.php?lang=<?= qp_h($locale) ?>&amp;theme_id=<?= $theme ?>"><?= $schema?$hub('Edit / add questions','Modifier / ajouter des questions'):$hub('Create questionnaire','Créer le questionnaire') ?></a><?php if($schema):?><a href="../survey_creator.php?lang=<?= qp_h($locale) ?>&amp;theme_id=<?= $theme ?>&amp;preview=1"><?= qp_h($hub('Preview questionnaire','Aperçu du questionnaire')) ?></a><?php endif;?></div>
<?php if($schema):?><p><label for="question-search"><?= qp_h($hub('Search questions','Rechercher une question')) ?></label> <input id="question-search" type="search" placeholder="<?= qp_h($hub('Text, code or competency…','Texte, code ou compétence…')) ?>"></p><p id="search-count" role="status"></p><div class="staff-table"><table><thead><tr><th><?= qp_h($hub('Question','Question')) ?></th><th><?= qp_h($hub('Type','Type')) ?></th><th><?= qp_h($hub('Maximum marks','Note maximale')) ?></th><th><?= qp_h($hub('Action','Action')) ?></th></tr></thead><tbody>
<?php foreach($questions as $q):?><tr data-question-row><td><strong><?= qp_h($q['questionCode']??$q['name']) ?></strong><div><?= qp_h($title($q['title']??$q['name'])) ?></div><?php if(($q['type']??'')==='multipletext'):?><ul><?php foreach($q['items']??[] as $item):?><li><?= qp_h($title($item['title']??$item['name'])) ?></li><?php endforeach;?></ul><?php endif;?><small><?= qp_h($hub('Competency:','Compétence :')) ?> <?= qp_h($q['competency']??'—') ?></small></td><td><?= qp_h($types[$q['type']]??$q['type']) ?></td><td><?= qp_h($displayMarks($q)) ?></td><td><a href="../survey_creator.php?lang=<?= qp_h($locale) ?>&amp;theme_id=<?= $theme ?>&amp;question=<?= rawurlencode($q['name']) ?>"><?= qp_h($hub('Edit','Modifier')) ?></a></td></tr><?php endforeach;?></tbody></table></div><?php endif;?></section><?php endif;?>
<details class="staff-card"><summary><?= qp_h($hub('Legacy question bank','Ancienne banque de questions')) ?></summary><p><?= qp_h($hub('Legacy questions and results remain available. To edit the published SurveyJS questionnaire, use the list above.','Les anciennes questions et leurs résultats restent disponibles. Pour modifier le questionnaire SurveyJS publié, utilisez la liste ci-dessus.')) ?></p><a href="questions.php?legacy=1&amp;lang=<?= qp_h($locale) ?>"><?= qp_h($hub('Open legacy bank','Ouvrir l’ancienne banque')) ?></a></details>
</main><script src="../assets/survey/questions-hub.js"></script></body></html><?php exit;
