<?php
require_once __DIR__.'/language.php';
$isAdmin=$role==='admin';
$headerPrefix=$staffRoot??'';
$staffLabel=static fn($en,$fr)=>currentLanguage()==='fr'?$fr:$en;
$staffLinks=$isAdmin?['index.php'=>'dashboard','course.php'=>'pu_course','manage_pages.php'=>'course_pages','themes.php'=>'themes','manage_content.php'=>'h150_course_content','questions.php'=>'questions','assign_questionnaire.php'=>'questionnaire_assignments','professors.php'=>'professors','trainees.php'=>'pkg_trainee_management','results.php'=>'pkg_trainee_results','course_results.php'=>'pu_course_results','levels.php'=>'positioning_levels']:['index.php'=>'dashboard','course.php'=>'pu_course','course_results.php'=>'pu_course_results','themes.php'=>'themes','content.php'=>'p150i_170767442d23','manage_content.php'=>'p150i_844717d6e9c8','structure.php'=>'p150i_b6b7c4908249','questions.php'=>'questions','trainees.php'=>'trainees_results','trainee_question_status.php'=>'questionnaire_status'];
$headerWords=['dashboard'=>['Dashboard','Tableau de bord'],'pu_course'=>['Course','Cours'],'course_pages'=>['Course Pages','Pages de cours'],'themes'=>['Themes','Thèmes'],'h150_course_content'=>['Course Content','Contenu du cours'],'questions'=>['Questions','Questions'],'questionnaire_assignments'=>['Questionnaire Assignments','Affectations de questionnaires'],'professors'=>['Professors','Formateurs'],'pkg_trainee_management'=>['Trainee management','Gestion des stagiaires'],'pkg_trainee_results'=>['Trainee results','Résultats des stagiaires'],'pu_course_results'=>['Course results','Résultats par cours'],'positioning_levels'=>['Positioning Levels','Niveaux de positionnement'],'p150i_170767442d23'=>['Content','Contenu'],'p150i_844717d6e9c8'=>['Course Content','Contenu du cours'],'p150i_b6b7c4908249'=>['Structure','Structure'],'trainees_results'=>['Trainee results','Résultats des stagiaires'],'questionnaire_status'=>['Questionnaire status','État des questionnaires']];
$headerText=static function($en,$fr)use($staffLabel){return '<span data-header-en="'.qp_h($en).'" data-header-fr="'.qp_h($fr).'">'.qp_h($staffLabel($en,$fr)).'</span>';};
$staffName=$isAdmin?($_SESSION['admin_username']??'admin'):($_SESSION['professor_name']??$staffLabel('Professor','Formateur'));
?>
<nav class="dashboard-language" aria-label="<?= qp_h($staffLabel('Language','Langue')) ?>">
<?php foreach(['en'=>'English','fr'=>'Français'] as $lang=>$name):?><a href="<?= qp_h(languageUrl($lang)) ?>" data-dashboard-language="<?= $lang ?>" <?= currentLanguage()===$lang?'aria-current="true"':'' ?>><?= $name ?></a><?php endforeach;?>
</nav>
<div class="dashboard-chrome">
<header class="dashboard-banner"><h1><?= $isAdmin?$headerText('Trainer Administration','Administration des formateurs'):$headerText('Professor Dashboard','Tableau de bord formateur') ?></h1><p><?= $headerText('Positioning Questionnaire Administration Portal','Portail d’administration du questionnaire de positionnement') ?></p><p><?= $headerText('Logged in as:','Connecté en tant que :') ?> <strong><?= qp_h($staffName) ?></strong></p></header>
<nav class="dashboard-navigation" aria-label="<?= qp_h($staffLabel('Navigation','Navigation')) ?>"><strong><?= $isAdmin?$headerText('Administrator Area','Espace administrateur'):$headerText('Professor Area','Espace formateur') ?></strong><div class="dashboard-nav-links">
<?php foreach($staffLinks as $url=>$key):$text=$key==='pu_course'?$staffLabel('Course','Cours'):($key==='pu_course_results'?$staffLabel('Course results','Résultats par cours'):t($key));?><a data-editor-nav href="<?= qp_h($headerPrefix.$role.'/'.$url.'?lang='.currentLanguage()) ?>" <?= $url==='questions.php'?'aria-current="page"':'' ?>><?= $headerText(...($headerWords[$key]??[$text,$text])) ?></a><?php endforeach;?></div>
<div class="dashboard-nav-links"><a data-editor-nav href="<?= qp_h($headerPrefix.'index.php?lang='.currentLanguage()) ?>"><?= $headerText('Homepage','Accueil') ?></a><a data-editor-nav href="<?= qp_h($headerPrefix.$role.'/logout.php') ?>"><?= $headerText('Logout','Déconnexion') ?></a></div><div class="dashboard-nav-links"><a data-editor-nav href="<?= qp_h($headerPrefix.'survey_results.php?lang='.currentLanguage()) ?>"><?= $headerText('Questionnaire results and marking','Résultats et corrections du questionnaire') ?></a></div></nav>
</div>
