<?php
// Keep the existing access checks in questionnaire.php and the original trainee UX.
require_once __DIR__.'/survey_app.php';
$definition=sv_row("SELECT * FROM survey_definitions WHERE theme_id=? AND status='published' ORDER BY id DESC LIMIT 1",[(int)$themeId]);
if(!$definition)return;
$survey=json_decode($definition['survey_json'],true,64,JSON_THROW_ON_ERROR);
$draftKey=(int)$traineeId.':'.($assignmentId?'assignment:'.(int)$assignmentId:'theme:'.(int)$themeId).':'.(int)$definition['id'];
$draft=$_SESSION['survey_drafts'][$draftKey]??['answers'=>[],'page'=>0];
$token=bin2hex(random_bytes(24));
$_SESSION['survey_runs'][$token]=['definition_id'=>(int)$definition['id'],'theme_id'=>(int)$themeId,'assignment_id'=>$assignmentId?(int)$assignmentId:null,'trainee_id'=>(int)$traineeId,'passation_type'=>$passationType,'created'=>time(),'draft_key'=>$draftKey];
foreach($_SESSION['survey_runs'] as $k=>$run)if(($run['created']??0)<time()-86400)unset($_SESSION['survey_runs'][$k]);
$fr=currentLanguage()==='fr';
$labels=$fr?['save'=>'Enregistrer mes réponses','saved'=>'Réponses enregistrées. Vous pouvez reprendre pendant cette session.','session'=>'La sauvegarde est conservée pendant votre session.','navigate'=>'Naviguer dans le questionnaire','answered'=>'répondues','unanswered'=>'sans réponse','progress'=>'Progression','competency'=>'Progression de la compétence','review'=>'Vérifier mes réponses','reviewTitle'=>'Vérification avant envoi','return'=>'Revenir au questionnaire','incomplete'=>'Aller à la première réponse manquante','confirm'=>'Confirmer et envoyer','saving'=>'Enregistrement en cours…','error'=>'Impossible d’enregistrer. Vos réponses restent affichées ; réessayez.','answer'=>'Votre réponse','next'=>'Suivant','previous'=>'Précédent']:['save'=>'Save my answers','saved'=>'Answers saved. You can resume during this session.','session'=>'Saved answers remain available during your session.','navigate'=>'Navigate the questionnaire','answered'=>'answered','unanswered'=>'unanswered','progress'=>'Progress','competency'=>'Competency progress','review'=>'Review my answers','reviewTitle'=>'Review before submission','return'=>'Return to the questionnaire','incomplete'=>'Go to the first unanswered question','confirm'=>'Confirm and submit','saving'=>'Saving…','error'=>'Unable to save. Your answers remain on screen; please retry.','answer'=>'Your answer','next'=>'Next','previous'=>'Previous'];
?><!doctype html><html lang="<?= qp_h(htmlLanguage()) ?>"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?= qp_h($definition['title']) ?></title>
<link rel="stylesheet" href="assets/css/style.css"><link rel="stylesheet" href="assets/css/trainee_language.css"><link rel="stylesheet" href="assets/css/ui.css"><link rel="stylesheet" href="assets/survey/vendor/survey-core.min.css"><link rel="stylesheet" href="assets/survey/legacy-ux.css"><script src="assets/js/ui.js" defer></script></head>
<body class="trainee-course"><div class="container"><?php require __DIR__.'/trainee_language_switcher.php'; ?><p><a href="index.php"><?= qp_h(t('h150_back_to_dashboard')) ?></a></p><hr>
<header class="questionnaire-header"><p class="eyebrow"><?= qp_h(t('h150_your_questionnaire')) ?></p><h1><?= qp_h($themeName) ?></h1><p class="mode-badge"><strong><?= qp_h(t('h150_questionnaire_label')) ?></strong> <?= qp_h(t($questionnaireMode==='assigned'?'h150_assigned_by_trainer':'h150_available_questionnaire')) ?></p><p><strong><?= qp_h(t('h150_passation_label')) ?></strong> <?= qp_h(traineePassationLabel($passationType)) ?></p><p><?= qp_h(t('qpx_instructions')) ?></p></header>
<main><section class="pu-progress"><p id="ux-progress-text" aria-live="polite"></p><progress id="ux-progress" value="0" max="1"></progress><div class="actions"><button id="ux-save" type="button"><?= qp_h($labels['save']) ?></button><span><?= qp_h($labels['session']) ?></span></div><p id="save-status" role="status"></p></section>
<div class="pu-test-layout"><aside class="pu-test-navigation"><button id="ux-toggle" type="button" aria-expanded="false" aria-controls="exercise-nav"><?= qp_h($labels['navigate']) ?> ▾</button><label class="sr-only" for="exercise-nav"><?= qp_h($labels['navigate']) ?></label><select id="exercise-nav" hidden><?php foreach($survey['pages']??[] as $index=>$page):?><option value="<?= $index ?>"><?= qp_h($page['title']??$page['name']) ?></option><?php endforeach;?></select></aside><div>
<header class="pu-competency"><h2 id="ux-competency"></h2><p id="ux-domain-text"></p><progress id="ux-domain-progress" value="0" max="1"></progress></header><div id="survey" class="question-block"></div>
<section class="submit-area"><button id="ux-review" type="button"><?= qp_h($labels['review']) ?></button></section>
<section id="ux-confirmation" class="pu-confirmation" hidden tabindex="-1"><h2><?= qp_h($labels['reviewTitle']) ?></h2><p id="ux-summary"></p><div class="actions"><button id="ux-return" type="button"><?= qp_h($labels['return']) ?></button><button id="ux-incomplete" type="button"><?= qp_h($labels['incomplete']) ?></button><button id="ux-confirm" type="button"><?= qp_h($labels['confirm']) ?></button></div></section>
</div></div></main></div>
<script src="assets/survey/vendor/survey.core.min.js"></script><script src="assets/survey/vendor/survey.i18n.min.js"></script><script src="assets/survey/vendor/survey-js-ui.min.js"></script><script>
window.questionnaireUX=<?= sv_json(['survey'=>sv_public($survey),'run'=>$token,'csrf'=>sv_csrf(),'draft'=>$draft,'locale'=>$fr?'fr':'en','labels'=>$labels]) ?>;
</script><script src="assets/survey/runtime.js"></script></body></html><?php exit;
